x-gui: &gui
  environment:
    DISPLAY: ${DISPLAY}
    XAUTHORITY: /tmp/.Xauthority
    QT_X11_NO_MITSHM: "1"
    NVIDIA_DRIVER_CAPABILITIES: ${NVIDIA_DRIVER_CAPABILITIES:-all}
  volumes:
    - type: bind
      source: /tmp/.X11-unix
      target: /tmp/.X11-unix
      read_only: true
    - type: bind
      source: ${XAUTHORITY}
      target: /tmp/.Xauthority
      read_only: true

services:
  cuda128-runtime:
    <<: *gui

  cuda128-devel:
    <<: *gui

  cuda130-runtime:
    <<: *gui

  cuda130-devel:
    <<: *gui